export const GAME_CONFIG = {
  mapWidth: 360,
  mapHeight: 216,
  legacyMapWidth: 90,
  legacyMapHeight: 54,
  worldExpansionOffsetX: 135,
  worldExpansionOffsetY: 81,
  maxTileHp: 5,
  attackDamage: 1,
  claimTokenCost: 1,
  attackTokenCost: 1,
  initialUserTokens: 100,
  maxActionPoints: 100,
  tileSize: 28,
  defaultTileDisplaySize: 32,
  minZoom: 0.02,
  maxZoom: 4,
  actionHighlightMinZoom: 0.55,
  detailedGridMinZoom: 0.35,
  coarseGridMinZoom: 0.08,
  coarseGridStep: 10,
  representativeImageFit: "cover" as const,
  representativeImageOpacity: 1,
  representativeImagePaddingRatio: 0.08,
  representativeImageMinZoom: 0.35,
  representativeImageTintOpacity: 0.12,
  representativeImageMinTileCount: 16,
  representativeImageMinWidthInTiles: 4,
  representativeImageMinHeightInTiles: 4,
  wheelZoomIntensity: 0.0015,
  maxWheelDelta: 120,
  dragThreshold: 5,
  viewportPadding: 24,
  mapEdgePadding: 72,
  minimapWidth: 165,
  minimapHeight: 99,
} as const;

export const DEFAULT_MAP_SIZE = {
  width: GAME_CONFIG.mapWidth,
  height: GAME_CONFIG.mapHeight,
} as const;
