begin;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in (
    'login', 'claim_success', 'attack_attempt', 'image_upload', 'supported_idol_change'
  )),
  created_at timestamptz not null default now()
);

create index if not exists profiles_created_at_idx on public.profiles(created_at);
create index if not exists activity_events_created_at_idx on public.activity_events(created_at);
create index if not exists activity_events_user_created_idx on public.activity_events(user_id, created_at);
create index if not exists activity_events_type_created_idx on public.activity_events(event_type, created_at);
create index if not exists idol_image_submissions_created_at_idx on public.idol_image_submissions(created_at);

alter table public.admin_users enable row level security;
alter table public.activity_events enable row level security;
revoke all on public.admin_users, public.activity_events from public, anon, authenticated;

create or replace function public.is_current_user_admin()
returns boolean language sql stable security definer set search_path = pg_catalog, pg_temp as $$
  select public.is_permanent_user()
    and exists(select 1 from public.admin_users where user_id = auth.uid())
$$;

create or replace function public.record_login_activity()
returns void language plpgsql security definer set search_path = pg_catalog, pg_temp as $$
declare v_user_id uuid := auth.uid();
begin
  if not public.is_permanent_user()
    or not exists(select 1 from public.profiles where user_id = v_user_id) then
    raise exception '로그인이 필요합니다.' using errcode='P0001';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(v_user_id::text || ':login', 0));
  if not exists(
    select 1 from public.activity_events
    where user_id = v_user_id and event_type = 'login'
      and created_at >= now() - interval '30 minutes'
  ) then
    insert into public.activity_events(user_id, event_type) values(v_user_id, 'login');
  end if;
end $$;

create or replace function public.capture_game_activity()
returns trigger language plpgsql security definer set search_path = pg_catalog, pg_temp as $$
declare v_user_id uuid := auth.uid(); v_event_type text;
begin
  if not public.is_permanent_user()
    or not exists(select 1 from public.profiles where user_id = v_user_id) then
    return new;
  end if;
  if tg_table_schema = 'public' and tg_table_name = 'tiles' and tg_op = 'INSERT' then
    v_event_type := 'claim_success';
  elsif tg_table_schema = 'public' and tg_table_name = 'tiles' and tg_op = 'UPDATE' then
    v_event_type := 'attack_attempt';
  elsif tg_table_schema = 'public' and tg_table_name = 'idol_image_submissions' and tg_op = 'INSERT' then
    v_event_type := 'image_upload';
  elsif tg_table_schema = 'public' and tg_table_name = 'players' and tg_op = 'UPDATE'
    and new.supported_idol_id is distinct from old.supported_idol_id then
    v_event_type := 'supported_idol_change';
  end if;
  if v_event_type is not null then
    insert into public.activity_events(user_id, event_type) values(v_user_id, v_event_type);
  end if;
  return new;
end $$;

drop trigger if exists capture_claim_activity on public.tiles;
create trigger capture_claim_activity after insert on public.tiles
for each row execute function public.capture_game_activity();
drop trigger if exists capture_attack_activity on public.tiles;
create trigger capture_attack_activity after update on public.tiles
for each row execute function public.capture_game_activity();
drop trigger if exists capture_image_upload_activity on public.idol_image_submissions;
create trigger capture_image_upload_activity after insert on public.idol_image_submissions
for each row execute function public.capture_game_activity();
drop trigger if exists capture_supported_idol_activity on public.players;
create trigger capture_supported_idol_activity after update of supported_idol_id on public.players
for each row execute function public.capture_game_activity();

create or replace function public.admin_get_summary()
returns jsonb language plpgsql security definer set search_path = pg_catalog, pg_temp as $$
declare
  v_now timestamptz := now();
  v_today_start timestamptz := date_trunc('day', v_now at time zone 'Asia/Seoul') at time zone 'Asia/Seoul';
begin
  if not public.is_current_user_admin() then
    raise exception '관리자 권한이 필요합니다.' using errcode='42501';
  end if;
  return jsonb_build_object(
    'total_users', (select count(*) from public.profiles),
    'new_users_today', (select count(*) from public.profiles where created_at >= v_today_start),
    'new_users_7d', (select count(*) from public.profiles where created_at >= v_now - interval '7 days'),
    'active_users_today', (select count(distinct user_id) from public.activity_events where created_at >= v_today_start),
    'active_users_7d', (select count(distinct user_id) from public.activity_events where created_at >= v_now - interval '7 days'),
    'total_image_uploads', (select count(*) from public.idol_image_submissions),
    'image_uploads_24h', (select count(*) from public.idol_image_submissions where created_at >= v_now - interval '24 hours')
  );
end $$;

revoke all on function public.is_current_user_admin() from public, anon;
revoke all on function public.record_login_activity() from public, anon;
revoke all on function public.admin_get_summary() from public, anon;
grant execute on function public.is_current_user_admin(), public.record_login_activity(), public.admin_get_summary() to authenticated;

commit;
